classDiagram

    Library "1" -- "0..*" Book : manages
    Library "1" -- "0..*" User : registers
    Library "1" -- "0..*" Loan : creates
    Book "1" -- "0..*" Loan : has
    User "1" -- "0..*" Loan : has

    
    class Library {
        +add_book(book: Book)
        +register_user(user: User)
        +create_loan(user: User, book: Book) Loan
    }
    class Book {
        +title: str
        +author: str
        +available: bool
        +mark_as_unavailable()
        +mark_as_available()
    }
    class User {
        +name: str
        +email: str
    }
    class Loan {
        +start_date: str
        +end_date: str
        +close_loan()
    }


